### ISSUE TITLE
How to solve/change this piece of code using cxsparse.

### ISSUE THREAD

**Issue by hsingla94** [ibayer/CXSparse#1]
How to solve/change this piece of code using cxsparse.

         SparseMatrix<double> A(cInd, kVar);
	 A.setFromTriplets(triplets.begin(), triplets.end());
	 Eigen::SPQR<SparseMatrix<double> > solver(A)
 	 VectorXd res = solver.solve(B.block(0,0,cInd,1));

Thanks ! cheers

**Comment by ibayer** [comment]
@hsingla94 
Sorry, I'm not the author of this library I just mirror it here for one of my projects.
You should be able to find the author here:
http://faculty.cse.tamu.edu/davis/suitesparse.html
